### ISSUE TITLE
Docker container logs not being collected

### ISSUE THREAD

**Issue by andy-a-o** [Microsoft/OMS-docker#89] opened 2018-01-25 14:29 UTC
## 1st case. Standalone Ubuntu server

1. Docker installed via apt.
2. Few containers are running.
3. OMS docker container running via command

`docker run --privileged -d -v /var/run/docker.sock:/var/run/docker.sock -v /var/log:/var/log e WSID="..." -e KEY="..." -p 127.0.0.1:25225:25225 -p 127.0.0.1:25224:25224/udp --name="omsagent" -h=test --restart=always microsoft/oms`

 - just as described here https://github.com/Microsoft/OMS-docker

Result: no container logs are collected, when looking inside omsagent container's /var/opt/microsoft/omsagent/e54f2b16-0fc5-4b80-a635-260e70a8dd31/log/omsagent.log

a few warnings found 

> 2018-01-25 09:10:21 +0000 [warn]: /var/lib/docker/containers/b8d84dcc623538481e0450fe72919b9df3283a801f2eac3e3e0360a0e747295a/b8d84dcc623538481e0450fe72919b9df3283a801f2eac3e3e0360a0e747295a-json.log is not readable. Cannot tail the file.
> 2018-01-25 09:10:21 +0000 [warn]: /var/lib/docker/containers/b1e55eec38746cb8d5c93bbff24c62552ffc0630c6cccc20ad4d6d3c84760fad/b1e55eec38746cb8d5c93bbff24c62552ffc0630c6cccc20ad4d6d3c84760fad-json.log is not readable. Cannot tail the file.
> 2018-01-25 09:10:21 +0000 [warn]: /var/lib/docker/containers/22411faf09a0933cc69a7a4567d01b3a6b9795b3b4d1c3b7e15b3a5ed0f77a00/22411faf09a0933cc69a7a4567d01b3a6b9795b3b4d1c3b7e15b3a5ed0f77a00-json.log is not readable. Cannot tail the file.
> 2018-01-25 09:10:21 +0000 [warn]: /var/lib/docker/containers/16ef7c7345513decddb7b42d965c56b68b7e7055f4c8d0e91aea7c57a9b2d95f/16ef7c7345513decddb7b42d965c56b68b7e7055f4c8d0e91aea7c57a9b2d95f-json.log is not readable. Cannot tail the file.
> 2018-01-25 09:10:21 +0000 [warn]: /var/lib/docker/containers/0632dceb120ff7053d3a7a3df59892a0016c8ce4aab01f69991fd8aad4b604c5/0632dceb120ff7053d3a7a3df59892a0016c8ce4aab01f69991fd8aad4b604c5-json.log is not readable. Cannot tail the file.
> 2018-01-25 09:10:21 +0000 [warn]: /var/lib/docker/containers/16185e569412c438bd4fa5c23089d9127dd85954799b87acddd83c8b1af7f13d/16185e569412c438bd4fa5c23089d9127dd85954799b87acddd83c8b1af7f13d-json.log is not readable. Cannot tail the file.

Adding this to the command:

`-v /var/lib/docker/containers:/var/lib/docker/containers`

solves the issue.

## 2nd case. Docker swarm.

1. Running Docker Swarm on Azure (https://docs.docker.com/docker-for-azure/)
2. OMS service started globally inside swarm as described here: https://github.com/Microsoft/OMS-docker/tree/master/Swarmmode

`docker service create --name omsagent --mode global --mount type=bind,source=/var/run/docker.sock,destination=/var/run/docker.sock -e WSID="<WORKSPACE ID>" -e KEY="<PRIMARY KEY>" -p 25225:25225 -p 25224:25224/udp --restart-condition=on-failure microsoft/oms`

Same result as above: no container logs are collected, when looking inside oms container same warnings are present. But the workaround above cannot be applied for Swarm.

Expected: container logs are collected in both cases.
`

**Comment by andy-a-o** [comment] 2018-01-25 17:48
So.. I suggest using Docker API instead of reading files

https://docs.docker.com/engine/api/v1.35/#operation/ContainerLogs

**Comment by andy-a-o** [comment] 2018-01-28 20:32
Finally switched to Kubernetes and it works fine.

**Comment by keikhara** [comment] 2018-02-22 23:32
For docker swarm, we realized there is a bug, We will be looking at this. For kubernetes, we will be publishing agent which enhances logs and other data for kubernetes.

**Comment by esuomi** [comment] 2018-02-28 14:15
@keikhara Any careful estimate when the bug will be fixed for Docker Swarm Mode? Just hit this today :)

**Comment by keikhara** [comment] 2018-03-01 17:10
@esuomi Can you try this with a different image tag? microsoft/oms:universe

**Comment by esuomi** [comment] 2018-03-02 08:53
Hi @keikhara I tried both universe and Feb28 tags and neither seemed to work. The reason I tried latter is because the universe tag is three months old and I had a bit of time to fiddle with this so thought why not... :)

**Comment by sarojgharat** [comment] 2018-03-23 08:39
Trying to use the microsoft/oms:latest version with kubernetes. But the container logs are not being collected. Any clues ?

**Comment by victornoel** [comment] 2018-04-19 15:27
@keikhara any news on this issue?

**Comment by victornoel** [comment] 2018-04-19 15:27
(using swarm mode and latest oms image)

**Comment by devteng** [comment] 2018-05-02 15:54
I used microsoft/oms:Mar6th and I am able to get the logs in Log Analytics from the PODS.

**Comment by victornoel** [comment] 2018-05-03 07:41
@devteng I think the problem is with swarm, not k8s.

For the record, I've tried latest version released 5 days ago but it's not fixing the problem.

**Comment by vishiy** [comment] 2018-05-09 17:40
I see 2 issues -
* Doc in github needs to be updated to a account for mounting the log volume
* Actual issue of  logs not being collected - this has been fixed with release on 4/27. Please pull latest/universe to pick up changes. 

@victornoel - Anything other then latest & universe are not for public consumption. They are for internal test.

**Comment by bragi92** [comment] 2018-05-10 17:32
updated the doc with `-v /var/lib/docker/containers:/var/lib/docker/containers`

**Comment by victornoel** [comment] 2018-05-11 06:52
@vimish when I said latest I meant the image with tag `latest` :)
@bragi92 thanks, I will experiment with this

**Comment by victornoel** [comment] 2018-05-11 06:53
@bragi92 does it apply also to swarm? In that case the documentation should be updated also for Swarm, no?

**Comment by bragi92** [comment] 2018-05-15 17:41
@victornoel where you successful with your experiment?

**Comment by victornoel** [comment] 2018-05-16 09:11
@bragi92 the documentation was updated in the main README.md, but it's not clear what is the actual expected parameters for Swarm. For example, in the main README.md, `/var/log` is also mounted, while it is not for Swarm.
Would it be possible to get an up to date documentation for Swarm too before I can try?
Thanks :)

**Comment by cyakimov** [comment] 2018-06-19 21:20
Hi, we're also facing the same issue; Docker logs (stdout/stderr) not being fed to Log Analytics. Any thoughts on why's that? 

Container is running in privileged mode with the following volume mounts:
```
- /var/run/docker.sock:/var/run/docker.sock
- /var/log:/var/log
- /var/lib/docker/containers:/var/lib/docker/containers
```

OS: `CoreOS stable (1745.7.0)`
Docker: `18.03.1-ce`
OMS Image: `microsoft/oms:universe`

**Comment by vishiy** [comment] 2018-06-19 23:21
@cyakimov - Are you seeing any errors in /var/opt/microsoft/omsagent/log/omsagent.log ?

**Comment by cyakimov** [comment] 2018-06-20 21:14
No, seems to be tailing logs from the 3 containers we have running. But nothing pops up when we search `ContainerLog` in the logs. 

```
2018-06-20 21:01:53 +0000 [info]: listening fluent socket on 0.0.0.0:25225
2018-06-20 21:01:53 +0000 [info]: listening syslog socket on 0.0.0.0:25224 with udp
2018-06-20 21:02:09 +0000 [info]: Following tail of /var/lib/docker/containers/0020abf9aee4a368966d4f6d3e62fda9a426ff5e5a98367451afe3eabfac3d2a/0020abf9aee4a368966d4f6d3e62fda9a426ff5e5a98367451afe3eabfac3d2a-json.log
2018-06-20 21:02:09 +0000 [info]: Following tail of /var/lib/docker/containers/1c33338e42fb9bb519b2bc088f7709599d5b41aaec5ece9154d16391224a0f0a/1c33338e42fb9bb519b2bc088f7709599d5b41aaec5ece9154d16391224a0f0a-json.log
2018-06-20 21:02:09 +0000 [info]: Following tail of /var/lib/docker/containers/0c6d74fa4bf667194486b494e767b2ff4ff193243c170a875a229973f0a730ee/0c6d74fa4bf667194486b494e767b2ff4ff193243c170a875a229973f0a730ee-json.log
2018-06-20 21:02:09 +0000 [info]: Following tail of /var/lib/docker/containers/9a12ff046580fb92d4236288cbb7ffea2ec1e93ae3767b0b23f76f05e30f9f59/9a12ff046580fb92d4236288cbb7ffea2ec1e93ae3767b0b23f76f05e30f9f59-json.log
2018-06-20 21:06:54 +0000 [info]: Sending OMS Heartbeat succeeded at 2018-06-20T21:06:54.178Z
```

**Comment by vishiy** [comment] 2018-06-20 21:32
thank you. can unpls check if the workspace has reached quota from azure portal? also are u seeing data other than logs from the same cluster?

**Comment by cyakimov** [comment] 2018-06-20 21:44
Is it possible that we have to enable `ContainerInsights` solution for the workspace in order to see container logs ?

**Comment by vishiy** [comment] 2018-06-20 22:03
@cyakimov - You need to add 'Container Monitoring Solution' to your workspace.
Please see here for more information - https://docs.microsoft.com/en-us/azure/log-analytics/log-analytics-containers

**Comment by esuomi** [comment] 2018-06-21 07:00
Hi,

By adding the `/var/lib/docker/containers:/var/lib/docker/containers` mount similar to @cyakimov  I now get the logs to Log Analytics which is great but Container Solution doesn't show anything making the readymade dashboard still a bit bleak.

There also seems to be an issue with multiline log entries but that's besides the point of this issue.

For reference, I'm running my Docker Swarm Mode service with (secrets hidden):
```bash
docker service create --name omsagent \
   --mode global \
   --mount type=bind,source=/var/run/docker.sock,destination=/var/run/docker.sock \
   --mount type=bind,source=/var/lib/docker/containers,destination=/var/lib/docker/containers \
   --mount type=bind,source=/var/log,destination=/var/log \
   --secret source=AZURE_WSID,target=WSID \
   --secret source=AZURE_KEY,target=KEY \
   -p 25225:25225 \
   -p 25224:25224/udp \
   --restart-condition=on-failure microsoft/oms
```

**Closed** 2018-06-27 18:38 UTC
Labels: bug
